spring:
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/main.xml

  datasource:
    url: jdbc:h2:file:~/spring-boot-h2-db
    username: sa
    password:

  h2:
    console:
      enabled: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate





